package com.yadong.sia.server.domain;

public class Roles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiao_roles.role_id
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiao_roles.xiao_roles
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    private String xiaoRoles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiao_roles.role_name
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiao_roles.role_disc
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    private String roleDisc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiao_roles.role_id
     *
     * @return the value of xiao_roles.role_id
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiao_roles.role_id
     *
     * @param roleId the value for xiao_roles.role_id
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiao_roles.xiao_roles
     *
     * @return the value of xiao_roles.xiao_roles
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public String getXiaoRoles() {
        return xiaoRoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiao_roles.xiao_roles
     *
     * @param xiaoRoles the value for xiao_roles.xiao_roles
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public void setXiaoRoles(String xiaoRoles) {
        this.xiaoRoles = xiaoRoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiao_roles.role_name
     *
     * @return the value of xiao_roles.role_name
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiao_roles.role_name
     *
     * @param roleName the value for xiao_roles.role_name
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiao_roles.role_disc
     *
     * @return the value of xiao_roles.role_disc
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public String getRoleDisc() {
        return roleDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiao_roles.role_disc
     *
     * @param roleDisc the value for xiao_roles.role_disc
     *
     * @mbggenerated Wed Feb 25 19:29:56 CST 2015
     */
    public void setRoleDisc(String roleDisc) {
        this.roleDisc = roleDisc;
    }
}