
package com.yadong.sia.server.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-03T08:12:56.977+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://WebXml.com.cn/", "IpAddressSearchWebService");

    public IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        System.out.println("cityByIp=60.10.123.206");
        IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap_Client  ipa = new IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap_Client();
//        ipa.getCityByIp("");
        String cityByIp = ipa.getCityByIp("60.10.123.206");
    	System.out.println("cityByIp="+cityByIp);
    	
    	
    }
    public  String getCityByIp(String ipAddr) throws Exception {
        URL wsdlURL = IpAddressSearchWebService.WSDL_LOCATION;
        if ( ipAddr != null && !"".equals(ipAddr)) { 
            File wsdlFile = new File(ipAddr);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(ipAddr);./
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
        }
      
        IpAddressSearchWebService ss = new IpAddressSearchWebService(wsdlURL, SERVICE_NAME);
        IpAddressSearchWebServiceSoap port = ss.getIpAddressSearchWebServiceSoap();  
        
       
        System.out.println("Invoking getCountryCityByIp...");
        java.lang.String _getCountryCityByIp_theIpAddress = "192.168.1.102";
        ArrayOfString _getCountryCityByIp__return = port.getCountryCityByIp(_getCountryCityByIp_theIpAddress);
        System.out.println("getCountryCityByIp.result=" + _getCountryCityByIp__return);


      
//        {
//        System.out.println("Invoking getVersionTime...");
//        java.lang.String _getVersionTime__return = port.getVersionTime();
//        System.out.println("getVersionTime.result=" + _getVersionTime__return);
//
//
//        }
//        {
//        System.out.println("Invoking getGeoIPContext...");
//        ArrayOfString _getGeoIPContext__return = port.getGeoIPContext();
//        System.out.println("getGeoIPContext.result=" + _getGeoIPContext__return);
//
//
//        }
        List<String> string = _getCountryCityByIp__return.getString();
//        String string2 = string.get(1);
        return string.get(1);
//        System.exit(0);
    }
   

}
